// ui
export const DISPLAY_POPUP = 'DISPLAY_POPUP'

// doule-eleven
export const DOULE_ELEVEN_ACTIVITY_LIST = 'DOULE_ELEVEN_ACTIVITY_LIST'

//	new-in
export const FETCH_NEW_IN_PRODUCT_LIST = 'FETCH_NEW_IN_PRODUCT_LIST'

//spring-festival
export const FETCH_RECTIVE_COUPONS = 'FETCH_RECTIVE_COUPONS'
export const FETCH_USER_COUPONS_EXTEND_CODE = 'FETCH_USER_COUPONS_EXTEND_CODE'
export const FETCH_USER_YEAR_LIST = 'FETCH_USER_YEAR_LIST'
export const GET_INVITATION_COUPONS = 'GET_INVITATION_COUPONS'


// red-envelope
export const RECEIVED_RED_ENVELOPE = 'RECEIVED_RED_ENVELOPE'
export const ERROR_RED_ENVELOPE = 'ERROR_RED_ENVELOPE'